parser: babel-eslint
extends:
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
settings:
  import/resolver: webpack
env:
  mocha: true
rules:
  max-len:
    - warn
    - code: 80
      tabWidth: 2
      ignoreComments: false
      ignoreTrailingComments: false
      ignorePattern: // # TOD: Add string literal regex.
      ignoreUrls: true
  func-names: off
  jsx-quotes: [1, "prefer-single"]
  object-property-newline: off
  no-unused-expressions: off # For chaijs tests.
  new-cap:
    - error
    - capIsNewExceptions: # Exceptions for ImmutableJS.
      - Map
      - List
  no-shadow: off
  no-nested-ternary: warn
  no-prototype-builtins: off
  no-extra-boolean-cast: off # https://github.com/airbnb/javascript#coercion--booleans
  no-multiple-empty-lines:
    - warn
    - max: 3
  no-global-assign: off # TODO: rule definition not found -- 160816
  react/jsx-filename-extension: off
  react/require-extension: off # TODO: deprecation warning.
  import/no-extraneous-dependencies: off
  import/no-commonjs: error
  import/no-amd: error
  import/imports-first:
    - error
    - absolute-first: false
