parser: babel-eslint
extends:
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - prettier/react
plugins:
  - prettier
settings:
  import/resolver: webpack
env:
  mocha: true
globals:
  fetch: true # Polyfilled in src/polyfills.js
rules:
  no-plusplus: off
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      printWidth: 79
  # import/no-unresolved: off # TODO: Handle webpack resolve.alias!
  import/no-extraneous-dependencies: off
  import/no-commonjs: error
  import/no-amd: error
  import/imports-first:
    - error
    - absolute-first: false
  # react/require-extension: off # TODO: deprecation warning -- 160816.
  react/jsx-filename-extension: off
  react/require-default-props: off
  no-unused-expressions: off # For chaij's tests.
  react/jsx-curly-spacing: off
