version: "3.3"
services:
  web:
    depends_on:
      - letsencrypt  # From api/docker-compose.prod.yaml
    environment:
      VIRTUAL_HOST: lawly.org,www.lawly.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_EMAIL: letsencrypt@lawly.org
      LETSENCRYPT_HOST: lawly.org,www.lawly.org,api.lawly.org,pg.lawly.org,redis.lawly.org
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory  # Staging Certs!
      DEBUG: "true"
