version: "3.3"
services:
  web:
    image: node:7
    container_name: lawly_web
    working_dir: /wd
    volumes:
      - ${WD:-/home/ubuntu}/web:/wd
      - /wd/node_modules
    command: npm run up
    ports:
      - 8000:8000
