#!/bin/zsh
APACHE_HOST=lawly@alnilam.uberspace.de
APACHE_PATH="~/html/app/"

[[ $(ssh-add -l) =~ .ssh/id_rsa ]] || ssh-add ~/.ssh/id_rsa

if [[ $@ != **nobuild** ]]; then
  echo "Build..."
  npm run build
fi

echo "S3...."
aws s3 cp dist/static/ s3://lawly --recursive --exclude="*" --include="app.*" --region eu-central-1

echo "Apache..."
scp -r dist/static/ ${APACHE_HOST}:${APACHE_PATH}
scp scripts/htaccess ${APACHE_HOST}:${APACHE_PATH}.htaccess
scp scripts/robots.txt ${APACHE_HOST}:${APACHE_PATH}

echo "Done."
