#!/bin/zsh
UBERSPACE="lawly@alnilam.uberspace.de:~/html/app"
UBERSPACE_WWW="lawly@alnilam.uberspace.de:~/html"
DIST=dist

[[ $(ssh-add -l) =~ .ssh/id_rsa ]] || ssh-add ~/.ssh/id_rsa

if [[ $@ != **nobuild** ]]; then
  echo "Build..."
  npm run build
fi

# Currently serving all statics from same origin because AppCache does not
# handle font CORS well..
# https://bugs.chromium.org/p/chromium/issues/detail?id=358744&thanks=358744&ts=1396376673
#if [[ $@ != **nos3** ]]; then
#  echo "S3...."
#  gzip -9 $DIST/app.*.js $DIST/*.css $DIST/MaterialIcons-*
#  rename -- .gz '' $DIST/*.gz
#  aws s3 cp $DIST/ s3://lawly --recursive --region eu-central-1 \
#    --content-encoding gzip --exclude="*" --cache-control max-age=604800 \
#    --include="app.*.js" --include="app.*.css" --include="MaterialIcons-*"
#fi

if [[ $@ != **nouber** ]]; then
  echo "Uberspace..."
  scp -r scripts/robots.txt $DIST/index.html $DIST/static $UBERSPACE/
  scp scripts/htaccess $UBERSPACE/.htaccess
  scp scripts/htaccessWWW $UBERSPACE_WWW/.htaccess
fi

echo "Done."
